export const APP_VERSION = "0.41.1";

export interface ChangelogEntry {
  version: string;
  date: string;
  type: "major" | "minor" | "patch";
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.41.1",
    date: "2026-05-12",
    type: "patch",
    changes: [
      "DASH-4.1: 'Compareceram' no Funil de Conversao agora usa a mesma fonte do KPI 'Comparecimento' (Appointment.statusKey='atendido' do Clinicorp)",
      "Bruno reportou inconsistencia: KPI 'Comparecimento' mostrava 1 mas funil 'Compareceram' mostrava 0",
      "Antes: lead.patient.procedures.some() — dependia de patientId estar populado no Lead e contava qualquer procedure (aprovado ou nao)",
      "Agora: lead.patient.appointments.some(statusKey='atendido', deleted=false) — fonte de verdade do Clinicorp, igual ao KPI da linha 2",
    ],
  },
  {
    version: "0.41.0",
    date: "2026-05-12",
    type: "minor",
    changes: [
      "DASH-4: linha nova de KPIs de comparecimento dos leads captados (vinda do Clinicorp) na Visao Geral",
      "Linha 1 (funil — Kommo): Leads captados / Consultas agendadas (renomeado, era 'realizadas') / Procedimentos fechados / Receita do funil",
      "Linha 2 (comparecimento — Clinicorp, FILTRADA pelo funil): Comparecimento ('Atendido' no Clinicorp) / Faltas (com taxa de no-show) / Confirmadas pendentes / Aguardando status",
      "Schema: modelo Appointment com clinicorpAppointmentId, date, statusKey ('agendado'|'confirmado'|'atendido'|'faltou'|'em_espera'|'em_atendimento'|'atrasado'). Migration 20260512000000",
      "Helper mapAppointmentStatus em src/lib/clinicorp/appointment-mapper.ts: 3 StatusIds canonicos confirmados com a equipe da clinica AD (5818=Atendido, 6447=Confirmado, 5434=Faltou) + fallback por StatusColor pra clinicas futuras. 11 unit tests",
      "Worker sync-clinicorp puxa /appointment/list a cada 15min, faz match patient via Patient_PersonId, upsert por clinicorpAppointmentId. Erro em appointments nao quebra sync de estimates",
      "Endpoint /api/dashboard ganha campo `consultas` com breakdown por statusKey, filtrado por patient com lead no pipelineId configurado (mesma logica de 'Procedimentos fechados' e 'Receita do funil')",
    ],
  },
  {
    version: "0.40.0",
    date: "2026-05-12",
    type: "minor",
    changes: [
      "Visual PR2: sidebar e header repaginados com a paleta laranja. Sidebar agora respira o tema (light = papel quente, dark = preto carvao), antes era sempre escura.",
      "Brand block da sidebar vira wordmark 'CliniFunnel' (Funnel em laranja) com microsubtitulo 'PAINEL CLINICO'. Removido o icone CF quadrado e o subtitulo 'Precision Analytics'.",
      "Item ativo da nav: fundo laranja translucido (12%) + texto laranja escuro + barra lateral 3px. Hover em cinza-papel sutil.",
      "Toggle de tema sai do rodape da sidebar e vira pill no header, junto com Sincronizar + avatar + Sair. Avatar agora tem gradiente laranja + sombra colorida (mesmo tratamento do icone do login).",
      "Header ganha sticky + backdrop-blur sobre o fundo papel/carvao.",
      "Consolidacao bg-gold/text-gold -> bg-primary/text-primary nos 10 usos do sidebar+header. Os 29 usos restantes em paginas internas seguem migrando automatico via alias --gold->--primary; consolidacao definitiva vira nos PRs 3+.",
    ],
  },
  {
    version: "0.39.0",
    date: "2026-05-11",
    type: "minor",
    changes: [
      "Visual: nova paleta laranja vivo (#FF7A1A) substitui o tema dourado/ambar; light mode 'Papel Quente' (fundo alabaster, sem branco puro) e dark mode 'Carvao Glow' (preto com glow laranja nos cantos)",
      "Login redesenhado: glass card centralizado sobre fundo com grid sutil e brilhos laranja; brand mark com icone 'C' em gradiente; pre-titulo 'PAINEL DE GESTAO', headline 'Acessar sua clinica' e link 'Esqueci minha senha'",
      "Toggle de modo (light/dark) no topo direito do login, persistido em localStorage; anti-flash via script inline no <head> aplica a classe 'dark' antes do paint",
      "Pagina /forgot-password placeholder ate o fluxo real de reset existir",
      "Token --gold mantido como alias visual de --primary (laranja vivo) pra absorver os 39 usos legados em dashboard/leads/sidebar/etc sem regressao; consolidacao bg-gold->bg-primary vira em PR2/3",
      "PR1 de 5 do redesign visual completo. Proximos: sidebar+header (PR2), dashboard overview (PR3), leads/demais telas (PR4), polimento (PR5)",
    ],
  },
  {
    version: "0.38.0",
    date: "2026-05-10",
    type: "minor",
    changes: [
      "DASH-3: dashboard agora reflete a 'Venda' como o Clinicorp calcula (- desconto, status nivel-procedure, exclui deletados)",
      "Bruno reportou R$ 67.480 (CliniFunnel) vs R$ 60.640 (Clinicorp Vendas) no periodo 3-9 mai. Investigacao identificou 3 problemas no sync: (a) status mapeado do Estimate.Status, mas 13 procs eram 'Orçamento' dentro de estimates APPROVED, (b) desconto da Estimate (R$ 4.160 no periodo) nao era capturado, (c) procs com Deleted='X' nao eram filtrados",
      "Schema: Procedure ganhou 4 campos novos — discountAmount (rateio proporcional), statusDescription ('Aprovado'/'Orçamento'/etc), paymentAccounted (boolean), deleted (boolean). Migration 20260510030000",
      "Helper mapEstimateToProcedures (src/lib/clinicorp/procedure-mapper.ts) ratea Estimate.DiscountAmount proporcional ao FinalAmount entre procs Aprovados, com ultimo proc absorvendo residuo de centavos. 15 unit tests novos cobrindo: rateio igual, residuo, deletados, sem aprovados",
      "Worker sync-clinicorp marca deleted=true em procs com Deleted='X' (pra procs que ja existiam no DB) e usa o helper pra inserir/atualizar com novos campos",
      "Dashboard/Financeiro/Procedimentos/Metrics filtram por statusDescription='Aprovado' + deleted=false em vez do legacy status IN ('approved','completed'). Receita = SUM(value - discountAmount)",
      "Receita esperada em prod: ~R$ 58.340 no range 3-9 mai (vs Clinicorp R$ 60.640, diff R$ 2.300 = sinais de consulta nao expostos na API publica do Clinicorp — gap aceito e documentado)",
    ],
  },
  {
    version: "0.37.0",
    date: "2026-05-10",
    type: "minor",
    changes: [
      "DASH-2: filtro de data de leads agora usa Lead.kommoCreatedAt (data de criacao no Kommo) em vez de Lead.createdAt (data de insercao no nosso DB)",
      "Antes: leads antigos do Kommo que mudavam de stage hoje viravam 'novos' nos ultimos 7d porque webhook so dispara em mudanca, e createdAt @default(now()) marca a primeira insercao",
      "Verificado em prod: filtro 'ultimos 7 dias' mostrava 26 leads (DB), Kommo mostrava 18 leads (kommoCreatedAt) — diferenca de 9 leads ruidosos, alguns criados ha mais de 1 ano no Kommo",
      "Aplicado em /api/dashboard, /api/metrics e /api/leads via helper buildLeadDateFilter em src/lib/dashboard-filters.ts",
      "OR no Prisma: usa kommoCreatedAt quando existe; cai pra createdAt apenas em leads legacy com kommoCreatedAt null (hoje 0 leads, mas mantido pra robustez)",
      "Listagem /api/leads tambem ordena por kommoCreatedAt (mais util que createdAt do DB pra leitura humana)",
      "5 unit tests novos cobrindo helper",
    ],
  },
  {
    version: "0.36.0",
    date: "2026-05-10",
    type: "minor",
    changes: [
      "DASH-1: card 'Composicao da receita' na Visao Geral mostra de onde vem cada centavo da clinica",
      "3 buckets somando 100%: Captacao (pacientes do pipeline atual), Recorrentes (pacientes de outros pipelines), Walk-ins (pacientes sem lead capturado)",
      "Cada bucket: valor R$, count de procedures e %",
      "Investigacao INT-3.2 mostrou que os '78 orfaos' (na verdade 162) eram procedures de pacientes do pipeline 'PACIENTES RECORRENTES' do Kommo — nao bug, mas faltava visibilidade",
      "API /api/dashboard ganhou campo receitaPorOrigem com {captacao, recorrentes, walkIn, total}",
      "Filtro de patientType (novo/existente) NAO aplica nos buckets — sao conceitos ortogonais (pipeline vs lead.isNewPatient)",
    ],
  },
  {
    version: "0.35.0",
    date: "2026-05-10",
    type: "minor",
    changes: [
      "INT-4: tela de Health da automacao Kommo->Clinicorp em /dashboard/settings/clinicorp/health",
      "Checklist visual em 1 olhada: configuracao Kommo/Clinicorp, mapa de profissionais, flags clinicorpAutoCreatePatient/clinicorpWebhookEnabled, sync periodico (lastSyncAt/lastMatchAt < 30min), atividade nas 24h, erros recentes",
      "Validacao opcional dos custom fields no Kommo via API (DATA E HORA CONSULTA + ATENDIDO POR) — carrega em paralelo com fallback se Kommo offline/token expirou, sem quebrar a tela",
      "Endpoint GET /api/clinics/[id]/health (DB-only) e /api/clinics/[id]/health/kommo-fields (chama Kommo)",
      "Helper computeHealthChecks em src/lib/clinicorp/health.ts (testavel) com 4 status: ok/warning/error/info e mensagem amigavel por item",
      "Reuso dos helpers hasAppointmentNameKeyword/hasTimeNameKeyword/isProfessionalField (exportados de src/lib/kommo/utm.ts) pra detecao bater com runtime",
      "Link 'Health automacao →' no header de /dashboard/settings",
      "21 unit tests novos cobrindo todos os status, edge cases e detecao de campos Kommo",
    ],
  },
  {
    version: "0.34.0",
    date: "2026-05-08",
    type: "minor",
    changes: [
      "INT-3: UI pra gerenciar o mapa de profissionais Kommo->Clinicorp em /dashboard/settings/clinicorp/professionals (antes so via SQL direto)",
      "Tabela editavel: linha por profissional com nome (Kommo) + ID (Clinicorp), botoes Adicionar/Remover/Cancelar/Salvar",
      "Endpoint GET/PUT /api/clinics/[id]/professional-map com RBAC (settings:read e settings:write)",
      "Validacao no servidor: nome nao vazio, ID inteiro positivo, sem duplicado case/whitespace insensitive",
      "Helper validateProfessionalMapInput em src/lib/clinicorp/professional-map.ts (testavel)",
      "Link 'Mapa de profissionais →' no header da pagina /dashboard/settings",
      "15 unit tests novos cobrindo validacao + dedup + edge cases",
    ],
  },
  {
    version: "0.33.0",
    date: "2026-05-08",
    type: "minor",
    changes: [
      "INT-3.1: sync automatico do Clinicorp e match-leads agora rodam a cada 15min (BullMQ repeat). Antes era so manual via botao no dashboard",
      "Fix: graficos 'Receita por periodo' (Visao Geral) e 'Receita por dia' (Financeiro) agrupam por data real do procedimento (COALESCE(completedAt, createdAt)) em vez de Estimate.CreateDate do Clinicorp",
      "Filtro de data (from/to) das mesmas queries tambem usa COALESCE pra coerencia com o agrupamento",
      "Schema: Clinic.lastClinicorpSyncAt e Clinic.lastMatchLeadsAt (DateTime?) — workers atualizam no fim de cada execucao bem sucedida",
      "Endpoint GET /api/sync/status retorna {lastSyncAt, lastMatchAt} pra clinica autenticada",
      "Header do dashboard mostra 'Atualizado ha Xmin' ao lado do botao Sincronizar (refresh automatico a cada 60s, repaint da label a cada 30s)",
      "Migration: prisma/migrations/20260508210000_clinic_sync_timestamps",
    ],
  },
  {
    version: "0.32.2",
    date: "2026-05-08",
    type: "patch",
    changes: [
      "INT-2.2: nome do paciente no Clinicorp vem do contato Kommo (completo) e nao do card (curto)",
      "INT-2.2: util phoneToClinicorp normaliza telefone antes de mandar pro Clinicorp (remove DDI 55, aceita varios formatos de entrada, preserva DDD 55 do RS)",
      "Aplicado em criacao de paciente e appointment",
      "7 unit tests novos cobrindo phoneToClinicorp",
    ],
  },
  {
    version: "0.32.1",
    date: "2026-05-08",
    type: "patch",
    changes: [
      "INT-2.1 (fix do teste end-to-end): email nao e mais obrigatorio pra criar paciente no Clinicorp (Clinicorp aceita sem email)",
      "extractAppointmentFields reconhece campo 'ATENDIDO POR' (usado pela clinica AD)",
      "Matcher do profissional aceita 'profissional', 'dentista', 'atendido' ou code='professional_id'",
      "2 unit tests novos cobrindo ATENDIDO POR",
    ],
  },
  {
    version: "0.32.0",
    date: "2026-05-07",
    type: "minor",
    changes: [
      "INT-2: Clinic.professionalMap (Json?) — mapeamento ATENDIDO POR (Kommo) -> Dentist_PersonId (Clinicorp)",
      "Helper resolveProfessionalId com lookup case e whitespace insensitive",
      "Worker create-patient resolve profissional via mapa (com fallback pra ID numerico direto)",
      "Migration adiciona coluna professionalMap (JSONB nullable)",
      "Cadastro do mapa via SQL nesta versao; UI vem em INT-3",
      "11 unit tests novos pro helper",
    ],
  },
  {
    version: "0.31.0",
    date: "2026-05-07",
    type: "minor",
    changes: [
      "INT-1: extractAppointmentFields suporta campo unico datetime (Kommo type=date_time)",
      "Detecta combinado por nome (data+consulta + hora) ou por field_type=date_time",
      "Split do unix timestamp em date 'YYYY-MM-DD' + time 'HH:MM' no fuso America/Sao_Paulo",
      "Backwards-compat: campos separados de data/hora continuam funcionando",
      "11 unit tests novos cobrindo combined, separados, profissional, edge cases",
    ],
  },
  {
    version: "0.30.1",
    date: "2026-05-07",
    type: "patch",
    changes: [
      "UI-1: KpiCard \"Receita do funil\" agora em verde (token success) em vez de gold",
      "Prop highlight aceita boolean | \"gold\" | \"green\" — backwards-compatible",
    ],
  },
  {
    version: "0.30.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "SEC-3: worker webhook-log-cleanup com retencao configuravel",
      "Default 90 dias (env WEBHOOK_LOG_RETENTION_DAYS); <= 0 desabilita",
      "Cron weekly (dom 03:00 UTC), batch 5000 logs por execucao",
      "Adicionado a QUEUE_NAMES — aparece automaticamente em /api/admin/queues e no painel /dashboard/logs",
      "Registrado em src/workers/index.ts com graceful shutdown",
    ],
  },
  {
    version: "0.29.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "SEC-2.1: WebhookLog ganha coluna clinicId (nullable) + index composto (clinicId, createdAt)",
      "Webhook handlers Kommo/Clinicorp populam clinicId apos identificar clinica",
      "/api/webhook-logs filtra por clinica: super_admin ve tudo + legacy nulls; clinic_admin so a propria; user bloqueado",
      "Resolve vazamento original do SEC-2 (clinic_admin via logs cross-tenant)",
      "Migration: prisma/migrations/20260506160000_webhooklog_clinicid",
      "Legacy entries (sem clinicId) ficam invisiveis pra clinic_admin — alternativa de mostrar reabriria o vazamento",
    ],
  },
  {
    version: "0.28.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "USR-1.3: RBAC granular por modulo (foundation)",
      "src/lib/permissions.ts: 10 modulos canonicos (leads, patients, campaigns, procedures, ltv, financeiro, logs, settings, users, ads) x 3 actions (read, write, delete)",
      "Modelo hibrido: role da baseline (super_admin tudo, clinic_admin quase tudo exceto delete users, user leitura operacional). User.permissions sobrescreve quando definido",
      "super_admin sempre passa (lockout protection mesmo com permissions vazia)",
      "PUT /api/users/[id]/permissions com sanitizacao de input (so modulos+actions canonicos)",
      "UI /dashboard/settings/users/[id]/permissions: radio baseline-vs-custom + grid de checkbox por modulo/action",
      "Botao Permissoes na tabela de users",
      "Hook useCanAccess(module, action) pra UI hide (defesa em profundidade — server e a verdade)",
      "RBAC aplicado em /api/sync (settings:write — usa tokens de integracao)",
      "permissions na session via JWT (auth.ts atualizado, login route route alinhada, types augmented)",
      "Tests: src/lib/permissions.test.ts (15 tests cobrindo super_admin, baselines, override explicit, sanitizacao)",
    ],
  },
  {
    version: "0.27.1",
    date: "2026-05-06",
    type: "patch",
    changes: [
      "docs: ONBOARDING.md (setup local + workflow + checklist nova rota/worker + debug)",
      "docs: DECISIONS.md em formato ADR — 11 decisoes arquiteturais documentadas com WHY + alternativas rejeitadas",
      "CLAUDE.md ganha bloco 'Documentos auxiliares' apontando pros 5 docs canonicos",
    ],
  },
  {
    version: "0.27.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "USR-1.2: UI admin de usuarios em /dashboard/settings/users",
      "Tabela de usuarios da clinica com badges de role e status (senha pendente vs ativo)",
      "Formulario novo usuario inline (email + nome + role)",
      "Apos create/reset: card destacado com senha temporaria + botao copiar (UMA UNICA exibicao com aviso 'nao sera mostrada de novo')",
      "Botao Resetar senha por linha (bloqueado pra super_admin)",
      "Link 'Gerenciar usuarios' no header da /dashboard/settings",
      "UI esconde silenciosa pra clinic_admin/user via 403 do backend (fonte de verdade)",
    ],
  },
  {
    version: "0.26.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "USR-1 foundation: criacao manual de usuarios (sem convite por email) + senha temporaria + forca troca no primeiro login",
      "Schema: User.mustChangePassword (Boolean) + User.permissions (Json?) — migration aplicada via prisma migrate deploy",
      "src/lib/users.ts: generateTemporaryPassword (12 chars cripto-random, charset sem 0/O/1/l/I) + hashPassword + verifyPassword + createUserWithTempPassword + resetUserPasswordToTemp + changeOwnPassword",
      "POST /api/users (clinic_admin/super_admin) cria usuario e retorna senha temp UMA UNICA VEZ",
      "POST /api/users/[id]/reset-password (admin) gera nova senha temp + reaplica flag",
      "POST /api/auth/change-password (qualquer user) troca propria senha exigindo a atual",
      "Middleware: redireciona pra /dashboard/change-password se mustChangePassword=true (so libera change-pw page e api + logout)",
      "Pagina /dashboard/change-password com formulario simples + signOut apos sucesso pra reciclar session",
      "auth.ts e next-auth.d.ts incluem mustChangePassword na session",
      "Logs estruturados em todas as rotas (criado/resetado/trocado) com userId, sem expor passwords (redact ja cobre)",
    ],
  },
  {
    version: "0.25.1",
    date: "2026-05-06",
    type: "patch",
    changes: [
      "/api/health expandido com campo `queues`: por fila waiting/failed counts + lastCompletedAt + lastFailedAt",
      "Reusa getAllQueues() exposto em [OBS-2]; timeout de 800ms; falha silenciosa retorna queues:null sem afetar o status agregado",
      "Status (ok|degraded) continua baseado SO em db+redis — worker travado nao tira a replica do pool do Traefik",
      "Util pra detectar workers travados externamente (ex: lastCompletedAt > 1h E waiting > 0)",
    ],
  },
  {
    version: "0.25.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "Endpoint /api/admin/queues (super_admin only) com metricas das 7 filas BullMQ",
      "Por fila: counts (waiting, active, completed, failed, delayed, paused), tempo medio dos ultimos 20 jobs, ultimo OK e ultimo fail",
      "Painel QueueMetricsPanel injetado no /dashboard/logs com refresh automatico a cada 10s",
      "Cards coloridos por estado: vermelho se ha falhas, ambar se ha jobs pendentes, neutro se idle",
      "Adicionada lista canonica QUEUE_NAMES + getAllQueues() em src/lib/queues.ts pra reuso",
      "Middleware /api/admin/* protegido (entrar no matcher de auth)",
    ],
  },
  {
    version: "0.24.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "Logs estruturados JSON com pino: 52 console.log/warn/error substituidos por logger com scope+contexto",
      "src/lib/logger.ts com redact paths pra mascarar tokens em logs (kommoToken, NEXTAUTH_SECRET, etc)",
      "Workers (7) usam logger.child({ scope: 'name' }) — log.info({ leadId, clinicId }, 'msg')",
      "Webhooks Kommo/Clinicorp e clinicorp/appointment.ts migrados",
      "Em dev: PRETTY_LOGS=1 ativa pino-pretty colorido. Em prod: JSON puro pra parsing por agregadores",
      "LOG_LEVEL configuravel (default info)",
    ],
  },
  {
    version: "0.23.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "Vitest configurado: 51 unit tests cobrindo crypto, phone, utm, OAuth state HMAC e auth-guard",
      "CI roda npm test entre tsc e build — falha de teste bloqueia merge",
      "vitest.config.ts + vitest.setup.ts (env defaults pra testes nao crasharem em modulos com fail-fast)",
      "Cobertura inicial focada em areas com risco historico: matching telefone (nono digito), criptografia AES-256-GCM (round-trip + tampering), HMAC anti-CSRF do OAuth, isolamento multi-tenant via auth-guard",
      "Foundation pronta — adicionar tests pra novas features e [QA-1.1] (integration tests com Postgres) seguem incremental",
    ],
  },
  {
    version: "0.22.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "Auditoria multi-tenant: catalogo de todas as 26 rotas API em docs/MULTITENANT-AUDIT.md",
      "fix CRITICO: /api/patients/[id] agora filtra por clinicId (antes findUnique so por id permitia cross-tenant access)",
      "fix: /api/webhook-logs restrito a super_admin ate WebhookLog ter coluna clinicId (issue [SEC-2.1] aberta)",
      "Documentado checklist pra novas rotas + grep checks pra nao regredir",
      "Confirmado HMAC-protection do state em OAuth callbacks (Google Ads, Meta) — sem patch necessario",
    ],
  },
  {
    version: "0.21.1",
    date: "2026-05-06",
    type: "patch",
    changes: [
      "fix: assertKeyAvailable() so roda fora do phase-production-build do Next",
      "Build do v0.21.0 quebrava no docker build porque next collect-page-data importa /api routes que importam @/lib/prisma -> assertKeyAvailable -> throw (chave nao esta no build context, deliberadamente)",
      "Em runtime (next start ou workers tsx) NEXT_PHASE != phase-production-build, validacao continua acontecendo",
    ],
  },
  {
    version: "0.21.0",
    date: "2026-05-06",
    type: "minor",
    changes: [
      "Tokens de integracao (Kommo, Clinicorp, Meta, Google) agora sao criptografados em repouso (AES-256-GCM)",
      "Novo src/lib/crypto.ts com encrypt/decrypt usando chave em INTEGRATION_TOKENS_KEY",
      "Prisma client extendido ($extends): encrypt automatico em writes e decrypt automatico em reads de Clinic",
      "Lazy migrate: tokens em texto claro continuam sendo lidos (compat) e sao re-encriptados no proximo write",
      "Script prisma/scripts/encrypt-existing-tokens.ts faz one-shot de migration nos clinics existentes",
      "Boot fail-fast: app nao sobe sem INTEGRATION_TOKENS_KEY definida (validacao em src/lib/prisma.ts)",
    ],
  },
  {
    version: "0.20.1",
    date: "2026-05-05",
    type: "patch",
    changes: [
      "docs: arquitetura de deploy Swarm documentada no CLAUDE.md (componentes, comandos, FASE 1 vs FASE 2)",
      "docs: runbook de cutover em docs/CUTOVER.md com pre-requisitos, janela e rollback",
      "fix: .env.production.example sem aspas (docker stack deploy nao consome aspas como compose) + warning explicito",
      "fix: runbook documenta o quirk e fornece sed pra corrigir env existente",
      "CLAUDE.md regra 7.1 atualizada: PM2 e nginx-proxy DEPRECATED",
      "Comandos uteis incluem operacao do dia-a-dia do swarm (logs, rollback, ps)",
      "IMPROVEMENTS.md fecha [INFRA-1] e abre [INFRA-2] (Fase 2 PG/Redis no swarm) e [INFRA-3] (build cache)",
    ],
  },
  {
    version: "0.20.0",
    date: "2026-05-04",
    type: "minor",
    changes: [
      "CI/CD migrado para build em GHA + push GHCR + deploy via docker stack deploy",
      "deploy.yml: 4 jobs (wait-ci, build, deploy, healthcheck) — sem mais build na VPS, RAM da VPS preservada",
      "Imagem privada ghcr.io/brunopalhardi/clinifunnel:latest + :sha-XXXXXXX para rollback",
      "Cache buildx via GitHub Actions (gha) para builds sequenciais rapidos",
      "scp-action sincroniza docker-stack.yml entre repo e VPS a cada deploy (infra-as-code)",
      "Healthcheck pos-deploy aceita status 'ok' ou 'degraded' (evita falso negativo durante warm-up)",
    ],
  },
  {
    version: "0.19.0",
    date: "2026-05-04",
    type: "minor",
    changes: [
      "Dockerfile refatorado: tini para signal handling, wget para healthcheck, remocao de copias redundantes de node_modules",
      "HEALTHCHECK no Dockerfile bate em /api/health a cada 30s",
      "docker-entrypoint.sh com log estruturado JSON e tratamento de erro explicito em prisma migrate",
      "docker-stack.yml novo (substitui docker-compose.prod.yml): swarm 3.8 com Traefik labels, healthcheck no service web, update_config start-first com rollback automatico",
      "Workers usam stop-first (evita 2 workers concorrendo na mesma queue BullMQ) e healthcheck disable",
      "Limites de recursos: web 600M, workers 200M (ajustado para VPS apertada)",
      ".env.production.example com vars necessarias (DB/Redis via host.docker.internal na FASE 1)",
      "docker-compose.prod.yml removido — Swarm ja existe na VPS, vamos usar",
    ],
  },
  {
    version: "0.18.0",
    date: "2026-05-04",
    type: "minor",
    changes: [
      "/api/health expandido: agora pinga Postgres (SELECT 1) e Redis (PING) com timeout de 800ms cada",
      "Resposta inclui campos db e redis (ok|down) e status agregado (ok|degraded)",
      "Sempre retorna 200 — Traefik usa o body pra decidir, evita downtime artificial em deploy single-replica",
      "Preparacao para Fase 1 da migracao Swarm: usado pelo healthcheck do docker service",
    ],
  },
  {
    version: "0.17.1",
    date: "2026-05-04",
    type: "patch",
    changes: [
      "Workflows com workflow_dispatch: permite disparo manual via 'gh workflow run' quando webhook do GitHub esta degradado",
      "deploy.yml aceita input skip-wait-ci=true para emergencia (uso documentado)",
      "CLAUDE.md regra 7.1: todo workflow critico deve ter workflow_dispatch + comandos de dispatch nos comandos uteis",
      "Fix: caminho do changelog em CLAUDE.md (publico /changelog, nao /dashboard/changelog)",
    ],
  },
  {
    version: "0.17.0",
    date: "2026-05-04",
    type: "minor",
    changes: [
      "Padrao de engenharia: CLAUDE.md reforcado (worktree obrigatoria, build local pre-PR, no merge direto em main)",
      "PR template com checklist obrigatorio (bump, lint, tsc, build, IMPROVEMENTS.md)",
      "Workflow CI: lint + tsc + build em cada PR e push (.github/workflows/ci.yml)",
      "Deploy aguarda CI verde + healthcheck pos-deploy em /api/health",
      "Backlog de melhorias rastreavel em docs/IMPROVEMENTS.md (5 eixos: seguranca, qualidade, observabilidade, multi-tenant, features)",
      "Versao visivel no rodape do login com link para /changelog",
      "Pagina publica /changelog renderizando o CHANGELOG tipado (antes vivia so no codigo)",
      "Sidebar: link da versao agora abre /changelog",
      "Rota /api/health retornando status, versao e timestamp (usada pelo deploy)",
    ],
  },
  {
    version: "0.16.1",
    date: "2026-04-27",
    type: "patch",
    changes: [
      "Fix: barras menores ficavam invisiveis (4px), agora minimo 6% da altura",
      "Fix: labels de data agora aparecem horizontais embaixo das barras",
      "Tooltip de receita aparece em destaque acima da barra ao passar o mouse",
    ],
  },
  {
    version: "0.16.0",
    date: "2026-04-27",
    type: "minor",
    changes: [
      "Receita por periodo: troca grafico fixo de 7 dias da semana por timeline real",
      "Granularity automatica: <=31 dias por dia, <=90 dias por semana, >90 dias por mes",
      "Tooltip com receita exata, scroll horizontal quando muitos pontos",
      "Label dinamico mostrando granularity ativo (Por dia/semana/mes)",
    ],
  },
  {
    version: "0.15.2",
    date: "2026-04-27",
    type: "patch",
    changes: [
      "DateFilter premium: calendario customizado com tema dark/gold (sem mais o feio nativo)",
      "Range selection: clica no inicio + clica no fim, com hover preview do range",
      "Layout reorganizado: atalhos a esquerda, calendario a direita",
    ],
  },
  {
    version: "0.15.1",
    date: "2026-04-27",
    type: "patch",
    changes: [
      "DateFilter modernizado: popover unico com presets (Hoje, Ontem, 7d, 30d, 90d, Este mes, Mes passado)",
      "Fix: 'Ate' agora pega ate o fim do dia (23:59:59) em vez de 00:00:00",
      "Fix: datas tratadas em horario local (nao UTC), evitando off-by-one",
      "Custom range com inputs de data + botao 'Aplicar periodo'",
    ],
  },
  {
    version: "0.15.0",
    date: "2026-04-27",
    type: "minor",
    changes: [
      "Nova aba Financeiro: caixa total da clinica (todos procedimentos)",
      "KPIs: receita confirmada, ticket medio, pacientes ativos, pipeline pendente",
      "Receita diaria, top 10 procedimentos, distribuicao por status",
    ],
  },
  {
    version: "0.14.0",
    date: "2026-04-27",
    type: "minor",
    changes: [
      "Matching de telefones agora normaliza o nono digito brasileiro (DDD + ultimos 8 digitos)",
      "Dashboard mostra Receita do funil + Receita total da clinica em paralelo",
      "Card 'Procedimentos fechados' inclui breakdown com total da clinica",
    ],
  },
  {
    version: "0.13.2",
    date: "2026-04-17",
    type: "patch",
    changes: [
      "Fix: forcar dynamic rendering em /dashboard/* e /login para Cloudflare nao cachear HTML",
      "Paginas antes estavam como static (prerendered) e recebiam s-maxage=31536000",
    ],
  },
  {
    version: "0.13.1",
    date: "2026-04-17",
    type: "patch",
    changes: [
      "Fix: adicionar no-cache em /dashboard, /login e / para evitar Cloudflare CDN servir HTML antigo",
      "Fix: command_timeout do deploy aumentado para 40m (build no VPS pode demorar >20m)",
    ],
  },
  {
    version: "0.13.0",
    date: "2026-04-16",
    type: "minor",
    changes: [
      "Fix: dashboard filtra leads apenas do pipeline 'Captacao de Leads'",
      "Segmentacao Novos vs Existentes: leads classificados como paciente novo ou retorno",
      "Toggle no dashboard para alternar entre Novos / Existentes / Todos",
      "Campo 'Canal de Prospeccao' capturado do Kommo e transferido para Clinicorp",
      "Validacao de campos obrigatorios antes de criar paciente no Clinicorp",
      "Automacao de agendamento no Clinicorp quando lead chega em 'Agendado'",
      "Dashboard LTV & ROAS com metricas por canal de aquisicao",
      "Pagina de listagem de pacientes com busca",
      "Perfil do paciente 360: timeline completa lead-to-procedure",
      "API de lembretes de retorno por procedimento (Botox 4m, Preenchimento 8m)",
    ],
  },
  {
    version: "0.12.0",
    date: "2026-04-16",
    type: "minor",
    changes: [
      "Multi-tenant: campo role no User (super_admin, clinic_admin, user)",
      "Auth guard: API routes validam que user tem acesso a clinica solicitada",
      "Super admin pode trocar entre clinicas via selector no header",
      "clinic_admin e user so acessam dados da propria clinica",
      "Seguranca: requests para clinicId nao autorizado retornam 403",
    ],
  },
  {
    version: "0.11.1",
    date: "2026-04-12",
    type: "patch",
    changes: [
      "Fix: telefone do lead agora e buscado via API de contatos do Kommo (antes tentava extrair do embed que nao trazia custom_fields)",
      "Novo metodo getContact() no KommoClient para buscar dados completos do contato",
      "field_code agora e case-insensitive (PHONE, Phone, phone todos funcionam)",
      "Logging de erro quando busca de contato falha",
    ],
  },
  {
    version: "0.11.0",
    date: "2026-04-12",
    type: "minor",
    changes: [
      "Funil agora mostra apenas dados de leads do Kommo (nao todos os procedimentos da clinica)",
      "Compareceram reflete dados reais: leads cujo paciente teve pelo menos 1 procedimento",
      "Auto-matching: quando procedimento chega do Clinicorp, vincula paciente a leads existentes por telefone",
      "Removidos trends hardcoded e porcentagens aleatorias do dashboard",
      "Corrigido SQL injection na query de receita por dia",
      "Receita e top procedimentos filtrados apenas por pacientes vinculados a leads",
    ],
  },
  {
    version: "0.10.1",
    date: "2026-04-06",
    type: "patch",
    changes: [
      "Fix: infinite re-render loop em todas as paginas do dashboard causado por referencia instavel do objeto clinic no useClinic hook",
      "useClinic agora usa useMemo para estabilizar referencia do objeto clinic",
    ],
  },
  {
    version: "0.10.0",
    date: "2026-04-04",
    type: "minor",
    changes: [
      "Integracao Meta Ads (Marketing API) — OAuth, sync automatico a cada 6h, somente leitura (ads_read)",
      "Integracao Google Ads — OAuth com refresh token, sync via GAQL, somente leitura",
      "Model AdCampaignData para armazenar dados de campanhas (spend, impressions, clicks) por dia",
      "API /api/campaigns enriquecida com dados de ad spend, CPL, CPC e ROI",
      "API /api/ads/status e /api/ads/disconnect para gerenciar conexoes",
      "Workers sync-meta-ads e sync-google-ads com BullMQ (repeat every 6h)",
      "Aba Anuncios no settings com botoes conectar/desconectar Meta e Google",
      "Pagina de campanhas redesenhada: KPIs (investimento, receita, ROI, CPL), grafico comparativo, tabela com plataforma e metricas de ads",
      "Compliance Meta: scope ads_read apenas, zero dados de pacientes enviados",
    ],
  },
  {
    version: "0.9.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Pagina Webhook Logs no dashboard com filtro por origem e visualizacao de payload JSON",
      "API /api/webhook-logs com filtros (source, status, limit)",
      "Link no sidebar para Webhook Logs",
      "Versao atualizada no sidebar",
    ],
  },
  {
    version: "0.8.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Toggles de integracao: receber webhooks Clinicorp (on/off) e criar pacientes automaticamente (off por padrao)",
      "Worker create-patient respeita flag clinicorpAutoCreatePatient",
      "Webhook Clinicorp respeita flag clinicorpWebhookEnabled",
      "Componente Switch adicionado ao UI kit",
      "Secao 'Controles de Integracao' na pagina de settings",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Botao Sincronizar funcional (dispara match-leads + sync-clinicorp)",
      "Filtros de data em todas as paginas do dashboard (presets 7/30/90 dias + custom)",
      "Home page redireciona para /dashboard",
      "API /api/sync implementada",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Webhook Clinicorp processa eventos de procedimentos e agendamentos",
      "Worker process-procedure: cria/atualiza procedures no banco com matching de paciente",
      "Mapeamento de status Clinicorp → status interno (pending/approved/completed/cancelled)",
      "Workers match-leads e sync-clinicorp registrados no index",
      "Todos os 4 workers com graceful shutdown",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Autenticacao com NextAuth (CredentialsProvider + JWT)",
      "Modelo User no Prisma vinculado a Clinic",
      "Middleware protegendo /dashboard e /api (exceto webhooks)",
      "Pagina de login com email + senha",
      "SessionProvider no layout, useClinic via session",
      "Header com nome do usuario e botao de logout",
      "Seed de usuario admin",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Settings backend funcional (GET/PUT /api/clinics/[id])",
      "POST /api/clinics para criar nova clinica",
      "Pagina de configuracoes com formularios Kommo e Clinicorp (Basic Auth)",
      "Tokens mascarados no GET, proteção contra sobrescrita com valor mascarado",
      "Badges de status de integração e webhook URLs dinâmicas",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Dashboard conectado a dados reais (KPIs, funil, leads, campanhas, procedimentos)",
      "API /api/metrics com metricas agregadas do funil",
      "API /api/procedures com listagem e filtros",
      "API /api/clinics para listagem de clinicas",
      "Hook useClinic para resolver clinica ativa",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-04-03",
    type: "minor",
    changes: [
      "Clinicorp client reescrito com Basic Auth (sem OAuth)",
      "Webhook captura todos os leads (add + status change)",
      "BullMQ worker cria paciente no Clinicorp ao atingir stage Agendado",
      "Seed da clínica AD com dados reais do Kommo e Clinicorp",
      "Banco PostgreSQL e Redis no servidor de produção",
      "Primeira migration aplicada",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-04-02",
    type: "minor",
    changes: [
      "Setup inicial do projeto",
      "Schema do banco (Clinic, Lead, Patient, Procedure, WebhookLog)",
      "Estrutura de pastas e arquivos base",
      "Docker Compose para dev (PostgreSQL + Redis)",
    ],
  },
];
